### ISSUE TITLE
Request for fetching [Ticket ID] - [Ticket Description]

### ISSUE THREAD

**Issue by chenop** [earvinpiamonte/jira-software-tool#3]
Thanks for open source this plugin!
I need the following format:
`[Ticket ID] - [Ticket Description]`

Is it something you could implement?

**Comment by earvinpiamonte** [comment]
Hello @chenop , thank you for submitting the issue. I'll put this feature on my to do list.

My plan is to update the options page wherein users can set the format of the string they need to copy, e.g. `[Ticket ID] - [Ticket Description]`.

Thanks.
